# Project
ext:
  appVersion: ${ext.appVersion}

# Swagger
springdoc:
  api-docs:
    path: /api-docs
    docs-format: openapi3
  ui:
    enabled: true
    path: /swagger-ui
    theme: dark

# Azure
azure:
  blob:
    account-name: {your account}
    account-key: { your account key }
    sas-duration: PT10M # 기본적으로 sasUrl 은 10분간 유효
